Filter evaluations endpoint by ground truth
ResonantGeoData/RD-WATCH pull request #110
Opened 2022-11-03 16:20 UTC by mvandenburgh

Only adds parameters to server endpoint, the frontend changes will follow in another PR.

2022-11-07 19:18 UTC, mcovalt commented
Looks good! I'll approve after the dependent branch [`paginate-site-evaluations`](https://github.com/ResonantGeoData/RD-WATCH/pull/109) gets merged. I believe GitHub will automatically update this PR to merge into `phase-ii` after that.

2022-11-08 20:54 UTC, mcovalt requested changes
I noticed a simple bug. On a request to `/api/evaluations?performer=KIT` I get a malformed "next" link: `/api/evaluations?performer=KIT?performer=KIT&page=2`.

2022-11-10 15:58 UTC, mvandenburgh commented
> I noticed a simple bug. On a request to `/api/evaluations?performer=KIT` I get a malformed "next" link: `/api/evaluations?performer=KIT?performer=KIT&page=2`.

Fixed :+1:

2022-11-14 20:44 UTC, mcovalt approved these changes

2022-11-14 21:20 UTC, merged