Remove dead/unused code
ResonantGeoData/RD-WATCH pull request #197
Opened 2023-05-13 18:37 UTC by mvandenburgh

- Removes a `dataclass` that is no longer used
- Remove the server status endpoint - this isn't used anywhere.

2023-06-02 15:46 UTC, BryonLewis requested changes
I'm using the server status to check to see that the container is healthy so I can start the celery container.  We either need to remove the migration from the entrypoint (which may be a good idea to prevent bad migrations).  Or find another way to prevent both the celery and django container in the dev environment from attempting to run migrations in parallel (something that can cause issues)

2023-06-05 15:09 UTC, mvandenburgh commented
> I'm using the server status to check to see that the container is healthy so I can start the celery container. We either need to remove the migration from the entrypoint (which may be a good idea to prevent bad migrations). Or find another way to prevent both the celery and django container in the dev environment from attempting to run migrations in parallel (something that can cause issues)

ok. For now I dropped that change, but I agree we should find a way to handle migrations better

2023-06-05 15:25 UTC, BryonLewis requested changes

2023-06-05 15:25 UTC, BryonLewis commented on django/src/rdwatch/dataclasses/server_status.py
> -    ip: str
I think that ./rdwatch/serializers/server_status.py needs this as an import?

2023-06-06 12:12 UTC, BryonLewis approved these changes
pulled, tested, and LGTM. :+1:

2023-06-06 14:37 UTC, merged