Properly serve static files in production
ResonantGeoData/RD-WATCH pull request #460
Opened 2024-07-29 16:25 UTC by mvandenburgh

This will fix the CSS issues on https://rgd.kitware.watch/admin/.

This PR is largely based on https://github.com/kitware-resonant/django-composed-configuration/blob/master/composed_configuration/_static.py

2024-07-29 17:25 UTC, BryonLewis requested changes
Just a question on the nginx route matching

2024-07-29 17:25 UTC, BryonLewis commented on docker/nginx.json
> +        "uri": "/staticfiles/*"
should this be /static/  The `STATIC_URL` in the settings.py is `static` the `STATIC_ROOT` which I think is the file location is `staticfiles`?

2024-08-02 16:45 UTC, mvandenburgh commented
This isn't working within docker, marking as draft until I can look into this

2024-10-01 01:55 UTC, mvandenburgh commented
Looking back into this, I don't think we even need `whitenoise` here. That package is used to serve static files from Python directly, and is useful for when you're running in an environment such as Heroku. But we're already using nginx, so we can just use that instead. I'll open another PR with that.

2024-10-01 01:55 UTC, closed without merging